# Generated by Django 2.0.6 on 2018-07-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='addreaa',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='branches',
            field=models.ManyToManyField(related_name='course', to='tasks.Branch'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(related_name='course', to='tasks.Category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='contacts',
            field=models.ManyToManyField(related_name='course', to='tasks.Contact'),
        ),
    ]
