# Generated by Django 2.0.6 on 2018-07-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180706_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.IntegerField(),
        ),
    ]
