# Generated by Django 2.0.6 on 2018-07-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180706_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='imgpath',
        ),
    ]
