# Generated by Django 2.0.6 on 2018-07-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_category_imgpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
